#!/usr/bin/env zsh

output_file=$1
vim_output_file=$2

if [ "$output_file" = "" ]; then
    echo "Error - pgpass output file not supplied"
    exit 1
fi

if [ "$vim_output_file" = "" ]; then
    echo "Error - vim database output file not supplied"
    exit 1
fi


echo "# odoo local
127.0.0.1:54320:odoo:odoo:odoo

# dp local
127.0.0.1:54399:demand_planner:demand_planner:demand_planner

# dp odoo local
127.0.0.1:54399:demand_planner_odoo:demand_planner:demand_planner
" > ${output_file}


echo "let g:dbext_default_profile='odoo_local'
let g:dbext_default_profile_odoo_local='type=pgsql:host=127.0.0.1:port=54320:user=odoo:dbname=odoo'
let g:dbext_default_profile_dp_local='type=pgsql:host=127.0.0.1:port=54399:user=demand_planner:dbname=demand_planner'
let g:dbext_default_profile_dp_odoo_local='type=pgsql:host=127.0.0.1:port=54399:user=demand_planner:dbname=demand_planner_odoo'" > ${vim_output_file}




for cc in $(ds-cluster-list | tail -n +2 | awk -F'|' '{print $2}'); do
    if use $cc; then
        port=$(ds-cluster-list | grep "|${cc}|"| awk -F'|' '{print $8}')

        # extract password for demand-planner
        if kubectl get secrets demand-planner-db-uri-secret -n demand-planner; then
            password=$(kubectl get secrets -n demand-planner demand-planner-db-uri-secret -o json | jq '.data."demand-planner-db-uri"' | xargs echo -n | base64 -D | sed -e 's/postgresql\:\/\/demand-planner\://g' -e 's/\@cloudsql-proxy-gcloud-sqlproxy.default.svc.cluster.local\:5432\/demand-planner//g')
            echo "# $cc" >> ${output_file}
            echo "127.0.0.1:${port}:demand-planner:demand-planner:${password}\n" >> ${output_file}
            echo "let g:dbext_default_profile_dp_${cc}='type=pgsql:host=127.0.0.1:port=${port}:user=demand-planner:dbname=demand-planner'" >> ${vim_output_file}
        else
            echo "$cc - demand-planner not found. ignore"
        fi
            
        # extract password for odoo 
        if kubectl get secrets odoo-db-secret; then
            odoo_password=$(kubectl get secrets odoo-db-secret -o json | jq '.data."db-password"' | xargs echo -n | base64 -D)
            echo "# $cc" >> ${output_file}
            echo "127.0.0.1:${port}:odoo:odoo:${odoo_password}\n" >> ${output_file}
            echo "let g:dbext_default_profile_odoo_${cc}='type=pgsql:host=127.0.0.1:port=${port}:user=odoo:dbname=odoo'" >> ${vim_output_file}
        else
            echo "$cc - odoo not found. ignore"
        fi
    else
        echo "$cc context switch failed"
    fi
done

