#!/usr/bin/env bash

file_name=$1

if [ "$file_name" = "" ]; then
    echo "[Error] No file name supplied"
    exit 1
fi

#disconnect all connection - drop and create demand-planner database
echo "select pg_terminate_backend(pg_stat_activity.pid) from pg_stat_activity where pg_stat_activity.datname = 'demand-planner' and pid <> pg_backend_pid(); drop database \"demand-planner\"; drop role if exists \"demand-planner\"; create user \"demand-planner\" with password 'demand_planner'; create database \"demand-planner\" owner \"demand-planner\";"\
    | psql -h localhost --port 54399 -U postgres -W;
echo "local demand-planner database dropped"

echo "Restore database - start"
psql -h localhost --port 54399 -U demand-planner -W < ./$file_name
echo "Restore database - done"
